### ISSUE TITLE
[Bug] Bug Title  The machine GUI interface does not display properly

### ISSUE THREAD

**Issue by upanawa** [MohistMC/AcademyCraft#4]
在MC1.12，mod版本1.1.4，模组内的除能力开发以外的机器GUI界面均无法正常显示，回退版本后问题消失

In MC1.12 and mod version 1.1.4, the GUI interface of the machine in the module except for capability development cannot be displayed normally, and the problem disappears after rolling back the version

**Comment by Mgazul** [comment]
Fixed
