### ISSUE TITLE
[Bug solution] Machines do not show the GUI properly

### ISSUE THREAD

**Issue by mohmedXM** [MohistMC/AcademyCraft#9]
In the file [src/main/scala/cn/academy/core/client/ui/TechUI.scala]

it contains

```Java
 override protected def drawGuiContainerBackgroundLayer(partialTicks: Float, mouseX: Int, mouseY: Int): Unit = {  
   }
``` 
at ContainerUI class
and it prevent the the machines to show the GUI properly
Deleting it shall solve the issue

**Comment by Mgazul** [comment]
Thanks for the help
